export const Mockingproperties = [
  {
    id: "1",
    title: "Modern Downtown Apartment",
    description: "Beautiful and spacious apartment in the heart of downtown",
    price: 450000,
    location: "Downtown, City",
    beds: 2,
    baths: 2,
    sqft: 1200,
    image: "/api/placeholder/400/300",
    type: "Apartment",
    features: ["Central AC", "Parking", "Pool"],
    slug: "modern-downtown-apartment",
  },
  {
    id: "2",
    title: "Luxury Beach House",
    description: "Stunning beachfront property with amazing ocean views",
    price: 850000,
    location: "Beachfront, Coast City",
    beds: 4,
    baths: 3,
    sqft: 2800,
    image: "/api/placeholder/400/300",
    type: "House",
    features: ["Ocean View", "Private Beach", "Garden"],
    slug: "luxury-beach-house",
  },
  {
    id: "3",
    title: "Cozy Suburban Home",
    description: "Perfect family home in a quiet suburban neighborhood",
    price: 350000,
    location: "Suburbia, State",
    beds: 3,
    baths: 2,
    sqft: 1800,
    image: "/api/placeholder/400/300",
    type: "House",
    features: ["Garage", "Backyard", "Fireplace"],
    slug: "cozy-suburban-home",
  },
];
